(function(g){var window=this;var p2=function(a){var b={languageCode:a.u,languageName:a.w,displayName:g.Iz(a),kind:a.A,name:a.B,id:a.H,is_servable:a.F,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.C};a.o&&(b.translationLanguage=a.o);return b},q2=function(a){return a.o?a.o.languageCode:a.u},hpa=function(a,b){var c=new g.Hz;
c.u=a.u;c.w=a.w;c.B=a.B;c.A=a.A;c.isDefault=!1;c.F=a.F;c.isTranslateable=a.isTranslateable;c.C=a.C;c.G=a.G;c.o=b;return c},ipa=function(){this.u=[];
this.o=[]},r2=function(a,b){return b?a.o.concat(a.u):a.o},s2=function(a,b){switch(b.A){case "asr":var c=a.u;
g.Xa(c,(0,g.x)(b.Wq,b))||c.push(b);break;default:c=a.o,g.Xa(c,(0,g.x)(b.Wq,b))||c.push(b)}},t2=function(a){g.E.call(this);
this.ab=a;this.u=new ipa;this.B=[]},u2=function(a,b,c){t2.call(this,a);
this.o=null;this.B=b.uu;this.w=c},v2=function(){this.o=[]},w2=function(a,b,c,d,e,f){g.E.call(this);
this.J=a;this.w=b;this.U=b.O();this.B=new v2;this.o=null;this.F=d;this.K=f;this.u=this.A=null;this.P=c;this.C=e||!1;this.G=new g.J(this.Jw,1E3,this);g.H(this,this.G);this.H=new g.Ss(this);g.H(this,this.H);this.H.M(b,"SEEK_COMPLETE",this.ox);this.ox();this.Jw()},x2=function(a,b){b-=a.w.yb();
var c=a.o;a.o=g.Va(a.P.Df(b).o);c!=a.o&&a.K&&a.K()},y2=function(a,b){var c=g.Aw(g.Lw(b,a.J,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.bq(c,d,3,100).then((0,g.x)(a.oK,a));a.A=b;c=a.B;d=a.A.o[0].u;var e=g.ob(c.o,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.o[e-1]&&e<c.o.length&&1==c.o[e]-d?(g.cb(c.o,e),g.cb(c.o,e-1)):0<e&&1==d-c.o[e-1]?c.o[e-1]=d:e<c.o.length&&1==c.o[e]-d?c.o[e]=d:(g.kb(c.o,e,0,d),g.kb(c.o,e+1,0,d)))},z2=function(a,b){t2.call(this,b.O());
this.o=a;this.F=b;this.w=null;this.A=!1;this.C=g.qz(this.F.O())&&!this.o.u},A2=function(a,b){var c=[],d;
for(d in a.o.o){var e=a.o.o[d];if(g.pP(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Hz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},jpa=function(a,b){return null!=b&&b in a.o.o?a.o.o[b]:null},B2=function(a,b,c){var d=[],e;
for(e in a.o.o){var f=a.o.o[e];if(g.pP(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},C2=function(a,b,c,d,e){t2.call(this,e||null);
c=c||g.hp(a).hl||"";c=c.split("_").join("-");this.A=g.jp(a,{hl:c});this.w=b;this.C=!!d;this.F={};this.o=null},D2=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.BD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.w=f;this.o=k},E2=function(a,b,c,d,e){g.BD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},G2=function(a){a=void 0===a?{}:a;
var b="_"+F2++;return new E2(0,0x8000000000000,0,b,a)},I2=function(a,b,c,d,e,f){var k={};
g.Ra(k,b);g.Ra(k,a.params);g.Ra(k,c);var l={};g.Ra(l,b.xb);a.params.xb&&g.Ra(l,a.params.xb);g.Ra(l,c.xb);k.xb=l;g.T.call(this,{D:"div",I:"caption-window",N:{id:"caption-window-"+a.id,dir:1==k.ze?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},L:[{D:"span",I:"captions-text",N:{style:"word-wrap: normal; display: block;"}}]});this.F=[];this.T=!1;this.A=a;this.aa=this.V=null;this.Na=e;this.Ma=f;this.G=null;this.ba=.96*e;this.ya=.96*f;this.w=k;this.Ha=c;this.C=this.u["captions-text"];this.Ba=
null!=this.C.style["box-decoration-break"]||null!=this.C.style["-webkit-box-decoration-break"];this.Z=d/360*16;this.type=0;this.na=this.Z*H2(l);a=new g.sL(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.GF,this);a.subscribe("dragmove",this.FF,this);a.subscribe("dragend",this.EF,this);this.xa=this.ra=0;b="";this.w.windowOpacity&&(a=g.KZ(this.w.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.w.windowOpacity+")");a={"background-color":b,display:!1===this.w.isVisible?"none":"","text-align":kpa[this.w.textAlign]};
this.Ba&&(a["border-radius"]=b?this.na/8+"px":"");if(this.B=2==this.A.params.ze||3==this.A.params.ze)b=this.element,c="vertical-rl",1==this.w.hA&&(c="vertical-lr"),g.Kd&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.eg(b,"-o-writing-mode",c),g.eg(b,"-webkit-writing-mode",c),g.eg(b,"writing-mode",c),g.eg(b,"text-orientation","upright"),g.K(b,"ytp-vertical-caption"),3==this.A.params.ze&&(g.eg(b,"text-orientation",""),g.eg(b,"transform","rotate(180deg)"));g.eg(this.element,a);switch(this.w.Yf){case 0:case 1:case 2:g.K(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.K(this.element,"ytp-caption-window-bottom")}},H2=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},J2=function(a,b){var c={},d=b.background?b.background:a.w.xb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.w.xb.backgroundOpacity;d=g.KZ(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ba&&(c["box-decoration-break"]="clone",c["border-radius"]=a.na/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*H2(b)+"px";d=1;e=b.color||a.w.xb.color;if(b.color||null!=b.textOpacity)e=g.KZ(e),d=null==b.textOpacity?a.w.xb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Cu&&(k=e=b.Cu);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=t;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Kp()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.w.xb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Te&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.zD&&(c.visibility="hidden");1==b.BD&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.Cu||g.sz,3==a.A.params.ze?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.ye||2==b.ye||3==b.ye||4==b.ye||5==b.ye)if(g.Cu)c["font-weight"]="bold";else switch(c["text-emphasis"]="filled circle",c["webkit-text-emphasis"]="filled circle",b.ye){case 4:case 3:c["text-emphasis-position"]="under left";c["webkit-text-emphasis-position"]=
"under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},K2=function(a){a.G=g.Rd("SPAN");
g.eg(a.G,{display:"block"});g.K(a.G,"caption-visual-line");a.C.appendChild(a.G)},L2=function(a,b){var c=g.Rd("SPAN");
g.eg(c,{display:"inline-block","white-space":"pre-wrap"});g.eg(c,J2(a,b));c.classList.add("ytp-caption-segment");a.G.appendChild(c);c.previousElementSibling&&(g.eg(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.eg(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},M2=function(a,b,c){a.T=a.T||!!c;
var d={};g.Ra(d,a.w.xb);g.Ra(d,c||b.o);g.Ra(d,a.Ha.xb);(c=!a.G)&&K2(a);for(var e=a.V&&a.aa&&g.ac(d,a.aa)?a.V:L2(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.w,n=k[l];m&&!c?(K2(a),e=L2(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Sd(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.Cu||!g.ig(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.ig(n.children[2],"text-emphasis-position")&&(m=a.B?"padding-left":"padding-bottom"),g.Md?
g.eg(e,m,"1em"):g.eg(e,m,"0.5em")))}a.aa=d;a.V=e;a.F.push(b)},N2=function(){},P2=function(){this.A=this.u=this.mode=this.w=0;
this.B=new O2(this);this.C=new O2(this);this.o=[];this.clear()},lpa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Ml:a,
Nl:b,result:0};a=Q2[a];b=Q2[b];if(a&128){if(!(b&128)&&0!=c.o&&c.u==b)return{Ml:a,Nl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Ml:a,Nl:b,result:2};return{Ml:a,Nl:b,result:3}},mpa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,R2(a.B,b,c,d))},npa=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.u=d.time;0==d.type?mpa(a,d.wu,d.xu,b):1==d.type&&a.w&496&&R2(a.C,d.wu,d.xu,b)}a.o.length=0},S2=function(){this.o=0},T2=function(){this.u=this.w=this.o=0},U2=function(){this.timestamp=this.Xd=0},V2=function(a){this.w=[];
for(var b=0;15>=b;b++){this.w[b]=[];for(var c=0;32>=c;c++)this.w[b][c]=new U2}this.o=this.u=this.row=0;this.style=new S2;this.B=a;this.A=0},W2=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.B.u+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.w[m][q];
if(0!=t.Xd){0==c&&(c=m,d=q);n=String.fromCharCode(t.Xd);var v=t.timestamp;v<e&&(e=v);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.Xd||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.u+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.w[k][m],t=q.Xd,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),v=q.timestamp,v<=e&&(e=v),l+=n,q.reset()),32==m||0==t)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},spa=function(a,b){switch(a){case 0:return opa[(b&127)-32];
case 1:return ppa[b&15];case 2:return qpa[b&31];case 3:return rpa[b&31]}return 0},X2=function(a){return a.w[a.row][a.u]},Y2=function(a,b,c){2<=b&&1<a.u&&(--a.u,X2(a).Xd=0);
var d=X2(a);d.timestamp=a.B.u+0;d.Xd=spa(b,c);32>a.u&&a.u++},Z2=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.w[b+e][f].gg(a.w[c+e][f])},$2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.w[b+d][e].reset()},a3=function(a){a.row=0<a.o?a.o:1;
a.u=1;$2(a,0,15)},b3=function(a){this.A=a;
this.B=0;this.style=new S2;this.C=new V2(a);this.F=new V2(a);this.G=new V2(a);this.u=this.C;this.w=this.F;this.o=this.u},c3=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:W2(d,c),a3(a.u),a3(a.w),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.A;e?d.u=1:d.o!=b&&(d.o>b?(W2(d,c),$2(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},d3=function(a){a.style.set(1);
a.o=a.w;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.A},e3=function(a){a.style.set(4);
a.o=a.G;a.o.style=a.style;a.A.mode=1<<a.o.A},O2=function(a){this.u=a;
this.o=new T2;this.B=0;this.w=new b3(a);this.C=new b3(a);this.A=this.w},R2=function(a,b,c,d){a.o.update();
b=lpa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Ml;c=b.Nl;if(32<=e||!e)a.u.mode&a.u.w&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.o,b&96&&Y2(a,0,b),c&96&&Y2(a,0,c),0!=b&&0!=c&&3==a.style.o&&W2(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.w=e,b.u=c,b.o=2,b=e&8?a.C:a.w,a.A=b,a.u.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.o?1:0),(a.u.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.o?1:0))&a.u.w))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;Z2(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));$2(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:Y2(b.o,0,32);break a;case 48:57==c?(d=b.o,X2(d).Xd=0,32>d.u&&d.u++):Y2(b.o,1,c&15)}break;case 2:c&32&&Y2(b.o,2,c&31);break;case 3:c&32&&Y2(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:d3(b);break;case 33:d=
b.o;1<d.u&&(--d.u,X2(d).Xd=0);break;case 36:d=b.o;b=X2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.w[a][c]==b){for(;32>=c;c++)d.w[a][c].reset();break}break;case 37:c3(b,2,d);break;case 38:c3(b,3,d);break;case 39:c3(b,4,d);break;case 40:Y2(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.A;break;case 42:d=b.G;d.o=15;d.style.set(4);a3(d);e3(b);break;case 43:e3(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:W2(a,d)}$2(a,0,15);break;case 45:b:{a=
b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;W2(a,d);Z2(a,b,b+1,a.o-1);$2(a,a.row,1)}break;case 46:$2(b.w,0,15);break;case 47:W2(b.u,d),b.w.updateTime(b.A.u+0),d=b.w,b.w=b.u,b.u=d,d3(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},f3=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.dd){var n=f[1],q=f[2],t=f[3];l.getAttribute("p");var v=g.Kp();l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");t.getAttribute("t");f=v?g.Rd("DIV"):g.Rd("RUBY");l=l.textContent;var y=g.Rd("SPAN");y.textContent=l;f.appendChild(y);n.getAttribute("p");y=v?g.Rd("DIV"):g.Rd("RP");l=n.textContent;y.textContent=l;f.appendChild(y);k=k[q.getAttribute("p")];l=q.textContent;q=v?g.Rd("DIV"):g.Rd("RT");q.textContent=l;f.appendChild(q);l=k.dd;if(10==l||11==l||12==l||13==l||14==l)if(g.eg(q,"text-emphasis",
"filled circle"),g.eg(q,"webkit-text-emphasis","filled circle"),k.dd==k.dd==11||13==k.dd)g.eg(q,"webkit-text-emphasis-position","under left"),g.eg(q,"text-emphasis-position","under left");q=!0;if(4==k.dd||7==k.dd||12==k.dd||14==k.dd)g.eg(f,"ruby-position","over"),g.eg(f,"-webkit-ruby-position","before");else if(5==k.dd||6==k.dd||11==k.dd||13==k.dd)g.eg(f,"ruby-position","under"),g.eg(f,"-webkit-ruby-position","after"),q=!1;t.getAttribute("p");l=t.textContent;t=v?g.Rd("DIV"):g.Rd("RP");t.textContent=
l;f.appendChild(t);v&&(v=q,g.eg(f,{display:"inline-block",position:"relative"}),t=f.firstElementChild.nextElementSibling,g.eg(t,"display","none"),t=t.nextElementSibling,g.eg(t,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.eg(f.lastElementChild,"display","none"),v?(g.eg(f,"padding-top","0.6em"),g.eg(t,"top","0")):(g.eg(f,"padding-bottom","0.6em"),g.eg(t,"bottom","0")));return new D2(a,b,e,c,f,d,m)}switch(m.dd){case 9:case 10:m.ye=
1;break;case 11:m.ye=2;break;case 12:m.ye=3;break;case 13:m.ye=4;break;case 14:m.ye=5}return new D2(a,b,e,c,l.textContent||"",d,m)},g3=function(){g.E.apply(this,arguments)},h3=function(a){g3.call(this);
this.w={};this.H={};this.J={};this.B="_"+F2++;this.C=a;this.G={};this.u=this.o=null;this.F=!0},i3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},j3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},k3=function(a,b){var c=i3(a,b);
return void 0!=c?c:null},m3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return l3.test(c),c},n3=function(a,b){var c={},d=b.getAttribute("ws");
g.Ra(c,d?a.J[d]:a.C);d=k3(b,"mh");null!=d&&(c.Pq=d);d=k3(b,"ju");null!=d&&(c.textAlign=d);d=k3(b,"pd");null!=d&&(c.ze=d);d=k3(b,"sd");null!=d&&(c.hA=d);d=m3(b,"wfc");null!=d&&(c.windowColor=d);d=i3(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},o3=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ra(c,a.H[d]);d=k3(b,"ap");null!=d&&(c.Yf=d);d=i3(b,"cc");null!=d&&(c.cm=d);d=i3(b,"ah");null!=d&&(c.Ue=d);d=i3(b,"rc");null!=d&&(c.Rk=d);d=i3(b,"av");null!=d&&(c.Kg=d);return c},p3=function(a,b,c,d){var e={};
g.Ra(e,o3(a,b));g.Ra(e,n3(a,b));d?g.ac(e,a.C)?(d=a.B,e=a.C):d="_"+F2++:d=b.getAttribute("id")||"_"+F2++;a=i3(b,"t")+c;b=i3(b,"d")||0x8000000000000;if(2==e.ze||3==e.ze)c=e.Rk,e.Rk=e.cm,e.cm=c;return new E2(a,b,0,d,e)},q3=function(a,b,c,d,e,f,k){I2.call(this,a,b,c,d,e,f,k);
this.type=1},r3=function(a,b,c){this.F=c;
this.version=this.C=this.A=this.o=0;this.u=new DataView(a);this.w=[]},s3=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},t3=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},u3=function(a,b){g3.call(this);
this.u=a;this.track="CC3"==b.w?4:0;this.o=new P2;this.o.w=1<<this.track},w3=function(a){if("string"===typeof a)return!1;
a=new r3(a,8,0);return v3(a)},v3=function(a){if(!(a.o<a.u.byteLength)||1380139777!=t3(a))return!1;
a.version=s3(a);if(1<a.version)return!1;s3(a);s3(a);s3(a);return!0},x3=function(a,b,c,d,e,f,k){I2.call(this,a,b,c,d,e,f,k);
g.K(this.element,"ytp-caption-window-rollup");this.type=2;this.H=[];this.K=this.J=this.fa=0;this.P=NaN;this.za=0;this.Ca=null;this.ga=new g.J(this.tK,433,this);g.H(this,this.ga);g.eg(this.element,"overflow","hidden")},tpa=function(a,b){return(a.B?b.offsetHeight:b.offsetWidth)+1},upa=function(a){if(isNaN(a.P)){var b=a.w.cm;
if(b){var c=g.Rd("SPAN");g.ce(c,"\u2013".repeat(b));g.eg(c,J2(a,a.w.xb));a.C.appendChild(c);a.P=c.offsetWidth;a.C.removeChild(c)}else a.P=0}return a.P},vpa=function(a,b){if(!b)return"";
a.B&&1!=a.A.params.hA&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},y3=function(a){a.H=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.A.params.Rk,c=0,d=0,e=a.H.length-1;c<b&&-1<e;){var f=a.H[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.H.length<b&&(d*=b/a.H.length);a.J=d;a.K=Math.max(upa(a),a.za,tpa(a,a.C))},wpa=function(a,b){y3(a);
var c=a.H.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.J-c;if(c!=a.fa){var d=0<c&&0==a.fa;b||isNaN(c)||d||(g.K(a.element,"ytp-rollup-mode"),g.cn(a.ga));g.eg(a.C,"transform",vpa(a,c));a.fa=c}y3(a)},z3=function(){g3.call(this)},A3=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Te=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType){q=new D2(b,c,d,e.id,q.nodeValue,f||0<n,g.Zb(l)?void 0:l);m.push(q);var t=e;g.H(t,q);t.o.push(q)}else t={},g.Ra(t,l),A3(a,b,c,d,e,!0,q,t,m)}},B3=function(a){var b=0;
a=g.p(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},C3=function(a,b,c,d){d=Object.assign({Pq:0},d);
return new E2(a,b,c,"_"+F2++,d)},D3=function(a){g.E.call(this);
this.u=a;this.o=null},G3=function(a){g.oP.call(this,a);
this.w=a.O();this.S=a.getVideoData();this.ra=g.uK(a);this.P=a;var b=null,c=g.Qn("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.An(c));this.da=b;this.A={xb:{}};this.C={xb:{}};this.J=[];this.U={};this.V={};this.K=!1;this.ga=g.qP(this.S,this.P);this.xa=!!this.S.captionTracks.length;this.ya=!!this.S.uj;this.ba="3"==this.w.controlsType;b=a.app.B;c=!(!b||!b.jl());this.na=!(!b||!b.Lh());this.B=this.ba&&c&&!this.ga;this.H=!this.B&&this.ba&&this.na&&this.ga;this.u=this.F=this.G=this.T=this.oa=
null;this.aa=new D3(this.w);g.H(this,this.aa);c=b=this.o=null;this.B||(b=new g.$m(this.xA,void 0,this),g.H(this,b),c=new g.J(this.UL,2E3,this),g.H(this,c));this.Z=b;this.fa=c;this.ea=new g.Ss(this);g.H(this,this.ea);this.B||this.ea.M(a,"resize",this.Rs);this.ea.M(a,"onPlaybackAudioChange",this.WH);this.ea.M(a,g.ED("captions"),this.HE,this);this.ea.M(a,"crx_captions",this.IE,this);E3(this,F3(this,"display-settings")||{})},H3=function(a){if(1==a.w.cg||1==a.S.cg||"alwayson"==g.qC(a.S,"yt:cc"))return!0;
if(2==a.w.cg){var b=F3(a,"module-enabled");if(null!=b)return!!b}if(a.S.captionTracks.length)var c=a.player.getAudioTrack().tp;return"ON"==c||"on"==g.qC(a.S,"yt:cc")},I3=function(a,b){if(a.o&&(void 0===b||!b)||!a.S.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.nm||"FORCED_ON"==c.tp},K3=function(a,b){if(a.u){if(a.F&&a.F.o)return a.F.o;
var c=b;c||(c=a.ya?!1:a.xa?!1:!0);c=r2(a.u.u,c);for(var d=[a.S.captionsLanguagePreference,a.w.captionsLanguagePreference,g.qC(a.S,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(q2(c[f])==d[e])return c[f];return a.F&&a.F.Dp?a.F.Dp:(d=c.find(function(k){return k.isDefault}))?d:c[0]||J3(a)}return null},J3=function(a){return a.F&&a.F.nm},L3=function(a){var b=J3(a);
return!!b&&a.o==b},M3=function(a,b){for(var c=a.P.app.B.fb().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},O3=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.K=c,a.K&&N3(a,"module-enabled",!!b));a.o=b;I3(a)&&(a.o=J3(a));a.load()},xpa=function(a,b){var c=a.ra.getVideoContentRect(!0).height;
if(!c)return null;var d=a.ra.getPlayerSize();switch(null!=b.params.Pq?b.params.Pq:1<b.o.length?1:0){case 1:return new q3(b,a.A,a.C,c,d.width,d.height,a.w.experiments);case 2:return new x3(b,a.A,a.C,c,d.width,d.height,a.w.experiments);default:return new I2(b,a.A,a.C,c,d.width,d.height,a.w.experiments)}},E3=function(a,b,c){var d=P3.xb;
a.A={};g.Ra(a.A,P3);a.A.xb={};g.Ra(a.A.xb,d);a.C={xb:{}};var e=b.backgroundOverride?a.C:a.A,f=b.background||d.background;l3.test(f);e.xb.background=f;e=b.colorOverride?a.C:a.A;f=b.color||d.color;l3.test(f);e.xb.color=f;e=b.windowColorOverride?a.C:a.A;f=b.windowColor||P3.windowColor;l3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.A;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.xb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.A;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.xb.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.A;e=b.fontStyle;null==e&&(e=d.bold&&d.Te?3:d.bold?1:d.Te?2:0);f=f.xb;switch(e){case 1:f.bold=!0;delete f.Te;break;case 2:delete f.bold;f.Te=!0;break;case 3:f.bold=!0;f.Te=!0;break;default:delete f.bold,delete f.Te}e=b.textOpacityOverride?a.C:a.A;f=b.textOpacity;null==f&&(f=d.textOpacity);e.xb.textOpacity=f;e=b.windowOpacityOverride?a.C:a.A;f=b.windowOpacity;null==f&&(f=P3.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.C:a.A;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.xb.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.A;f=b.fontFamily;null==f&&(f=d.fontFamily);e.xb.fontFamily=f;a.loaded&&a.Rs();c&&N3(a,"display-settings",b)},R3=function(a,b){if(b&&!a.G){var c=G2({ze:0,
lang:"vi"});a.G=[c,new D2(c.start,c.end-c.start,0,c.id,"Ph\u1ee5 \u0111\u1ec1 tr\u00f4ng nh\u01b0 th\u1ebf n\u00e0y")];g.IK(a.player,a.G)}else!b&&a.G&&(Q3(a,a.G),a.G=null)},Q3=function(a,b){g.$S(a.player.app,b,void 0);
(0,g.z)(b,function(c){g.db(this.J,c)},a);
a.Z.ii()},F3=function(a,b){if(!a.da)return null;
try{var c=a.da.get(b)}catch(d){a.da.remove(b)}return c},N3=function(a,b,c){if(a.da)try{a.da.set(b,c)}catch(d){}};
g.Hz.prototype.Wq=g.ca(11,function(a){return a?this.toString()==a.toString():!1});
g.Yu.prototype.Bm=g.ca(10,function(a){return(a=this.lg(a))?a.o:0});
g.cx.prototype.Bm=g.ca(9,function(){return 0});
g.Bt.prototype.wj=g.ca(8,function(){for(var a=g.Dd(document,"track",void 0,this.o),b=0;b<a.length;b++)g.Yd(a[b])});
g.bR.prototype.wj=g.ca(7,function(){this.o.wj()});
g.Bt.prototype.jl=g.ca(6,function(){return!!this.o.textTracks});
g.bR.prototype.jl=g.ca(5,function(){return this.o.jl()});
g.Bt.prototype.oj=g.ca(4,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.bR.prototype.oj=g.ca(3,function(a){this.o.oj(a)});
g.qt.prototype.Lh=g.ca(2,function(){});
g.Bt.prototype.Lh=g.ca(1,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.bR.prototype.Lh=g.ca(0,function(){return this.o.Lh()});
var ypa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,l3=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(t2,g.E);t2.prototype.jz=function(){return!1};
t2.prototype.Y=function(){this.Lg();g.E.prototype.Y.call(this)};
g.r(u2,t2);u2.prototype.Nq=function(a,b,c){b=this.Rj(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Lg();this.o=g.Bp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
u2.prototype.Oq=function(a){if(this.w)for(var b=g.p(this.w.captionTracks),c=b.next();!c.done;c=b.next())s2(this.u,c.value);a()};
u2.prototype.Rj=function(a,b){var c=a.G,d={fmt:b};if("srv3"==b||"3"==b)g.Kp()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.o&&(d.tlang=q2(a));return g.jp(c,d)};
u2.prototype.Lg=function(){this.o&&this.o.abort()};
v2.prototype.contains=function(a){a=g.ob(this.o,a);return 0<=a||0>a&&1==(-a-1)%2};
v2.prototype.length=function(){return this.o.length/2};
g.r(w2,g.E);g.h=w2.prototype;g.h.Y=function(){g.E.prototype.Y.call(this);this.u&&this.u.cancel()};
g.h.ox=function(){x2(this,this.w.getCurrentTime())};
g.h.reset=function(){this.B=new v2;this.u&&(this.u.cancel(),this.u=null)};
g.h.Jw=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.Nf(a);!a||this.u||this.o&&30<this.o.startTime-this.w.getCurrentTime()||(a=this.o,a=a.o.Bi(a),a.o[0].duration?(this.B.contains(a.o[0].u)||y2(this,a),this.o=g.Va(a.o)):!g.P(this.U.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.B&&this.o.B+this.w.yb()<this.w.getCurrentTime()&&x2(this,this.w.getCurrentTime()));this.G.start()};
g.h.oK=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.hx(a);c?(a=g.Lw(this.A,this.J,{}),b=this.A,g.Hw(b.u,a,c),b.requestId=a.get("req_id"),y2(this,this.A)):(b||null===this.F||(c=this.A.o[0],this.C?this.F(a.response,1E3*(c.startTime+this.w.yb())):this.F(a.responseText,1E3*(c.startTime+this.w.yb()))),this.u=this.A=null)};
g.r(z2,t2);g.h=z2.prototype;g.h.Nq=function(a,b,c){this.Lg();b=jpa(this,a.getId());b||(b=a.u,b=this.o.u?B2(this,b,"386"):B2(this,b));if(b){var d=1E3*(b.index.Bm(b.index.se())-b.index.Oc(b.index.se()));this.w=new w2(new g.Cw,this.F,b,function(e,f){c(e,a,f,d)},this.C||g.Bs(b.info),(0,g.x)(function(){this.w&&this.w.reset();
this.A=!0},this))}};
g.h.jz=function(){var a=this.A;this.A=!1;return a};
g.h.Oq=function(a){var b;this.C?b=[new g.Hz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Hz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.o.u?A2(this,"386"):A2(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())s2(this.u,c.value);a()};
g.h.Lg=function(){this.w&&(this.w.dispose(),this.w=null)};
g.h.Rj=function(){return""};
g.r(C2,t2);C2.prototype.Nq=function(a,b,c){b=this.Rj(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Lg();this.o=g.Bp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
C2.prototype.Oq=function(a){var b=this.A,c={type:"list",tlangs:1,v:this.w,vssids:1};this.C&&(c.asrs=1);b=g.jp(b,c);c=(0,g.x)(function(d){this.o=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.p(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),q=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),v="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
s2(this.u,new g.Hz({languageCode:f,languageName:l,name:m,kind:n,id:q,is_servable:!0,is_translateable:v,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),q=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:q,isDefault:t},this.F[l.languageCode]=l.languageName,this.B.push(l)}a()},this);
this.Lg();this.o=g.Bp(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
C2.prototype.Rj=function(a,b){var c=this.A,d={v:this.w,type:"track",lang:a.u,name:a.getName(),kind:a.A,fmt:b};a.o&&(d.tlang=q2(a));return c=g.jp(c,d)};
C2.prototype.Lg=function(){this.o&&this.o.abort()};var kpa=["left","right","center","justify"];var P3={windowColor:"#080808",windowOpacity:0,textAlign:2,Yf:7,Ue:50,Kg:100,xb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(D2,g.BD);D2.prototype.toString=function(){return g.BD.prototype.toString.call(this)};g.r(E2,g.BD);E2.prototype.toString=function(){return g.BD.prototype.toString.call(this)};
var F2=0;g.r(I2,g.T);g.h=I2.prototype;g.h.GF=function(a,b){var c=g.ug(this.element,this.element.parentElement);this.ra=a-c.x;this.xa=b-c.y;g.K(this.element,"ytp-dragging")};
g.h.FF=function(a,b){var c=g.xg(this.element),d=a-this.ra-.02*this.Na,e=b-this.xa-.02*this.Ma,f=(d+c.width/2)/this.ba*3;f=Math.floor(g.pd(f,0,2));var k=(e+c.height/2)/this.ya*3;k=Math.floor(g.pd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ba;d=100*g.pd(d,0,1);c=(e+k/2*c.height)/this.ya;c=100*g.pd(c,0,1);this.A.params.Yf=l;this.A.params.Kg=c;this.A.params.Ue=d;this.w.Yf=l;this.w.Kg=c;this.w.Ue=d;this.Jz()};
g.h.EF=function(){g.mn(this.element,"ytp-dragging")};
g.h.Jz=function(){this.Hh(this.F)};
g.h.Hh=function(a){var b=Math.min(this.Bv(),this.ba),c=this.Av(),d="";3==this.A.params.ze&&(d="rotate(180deg)");g.eg(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.gp(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.w.Ue+2;d=this.w.Yf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.w.Kg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.eg(this.element,a)};
g.h.gp=function(a){var b;for(b=0;b<a.length&&a[b]==this.F[b];b++);if(this.T||this.F.length>b)b=0,this.T=!1,this.F=[],this.G=this.aa=this.V=null,g.Ud(this.C);for(;b<a.length;b++)M2(this,a[b])};
g.h.Bv=function(){return 0};
g.h.Av=function(){return 0};
g.h.toString=function(){return g.T.prototype.toString.call(this)};N2.prototype.B=function(){};P2.prototype.clear=function(){this.A=this.u=this.mode=0;this.o=[];this.reset()};
P2.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var Q2=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];S2.prototype.set=function(a){this.o=a};
S2.prototype.get=function(){return this.o};
T2.prototype.clear=function(){this.o=0};
T2.prototype.update=function(){this.o=2==this.o?1:0};
T2.prototype.matches=function(a,b){return 0!=this.o&&a==this.w&&b==this.u};
U2.prototype.gg=function(a){this.Xd=a.Xd;this.timestamp=a.timestamp};
U2.prototype.reset=function(){this.timestamp=this.Xd=0};
V2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.w[b][c].timestamp=a};
V2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.w[b][c];a=0==d.Xd?a+"_":a+String.fromCharCode(d.Xd)}a+="\n"}return a};
V2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.w[b][c].reset();this.A=a;this.o=0;this.u=this.row=1};
var opa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],ppa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],qpa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],rpa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];b3.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.u=this.C;this.w=this.F;this.o=this.u;var c=(a<<2)+(b<<1);this.C.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
O2.prototype.reset=function(a){this.B=a;this.o.clear();this.A=this.w;this.w.reset(a,0);this.C.reset(a,1)};g.r(g3,g.E);g3.prototype.reset=function(){};g.r(h3,g3);h3.prototype.reset=function(){this.G={};this.u=this.o=null;this.F=!0};
h3.prototype.A=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.w,l={},m=c.getAttribute("p");m&&g.Ra(l,this.w[m]);m=j3(c,"b");null!=m&&(l.bold=
m);m=j3(c,"i");null!=m&&(l.Te=m);m=j3(c,"u");null!=m&&(l.underline=m);m=k3(c,"et");null!=m&&(l.charEdgeStyle=m);m=k3(c,"of");null!=m&&(l.offset=m);m=m3(c,"bc");null!=m&&(l.background=m);m=m3(c,"ec");null!=m&&(l.Cu=m);m=m3(c,"fc");null!=m&&(l.color=m);m=k3(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=i3(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=i3(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=i3(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=k3(c,"rb");null!=m&&10!=m&&0!=m&&(l.dd=10<m?m-1:m);
m=k3(c,"hg");null!=m&&(l.BD=m);c=k3(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.ye=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.J[d]=n3(this,c);break;case "wp":d=c.getAttribute("id"),this.H[d]=o3(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=p3(this,d,e,!1);g.H(this,this.o);(d=this.G[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.G[this.o.id]=this.o;c.push(this.o);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.B;m=!!j3(d,"a");n=(i3(d,"t")||0)+n;var q=i3(d,"d")||5E3;m||(!this.F&&this.u&&this.u.windowId==l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"==this.u.text&&(this.u.text=""));var t=m?6:5,v=this.w[d.getAttribute("p")],y=[].concat(g.ea(d.childNodes));y.length&&(this.F=null!=d.getAttribute("d"));for(var B=0;B<y.length;B++){var C=y[B],G=void 0;0<B&&(m=!0);var I=void 0;1==C.nodeType&&(I=C);if(I&&"s"==I.tagName){if((C=this.w[I.getAttribute("p")])&&C.dd&&(1==C.dd?(C=y.slice(B,
B+4),4==C.length&&(G=f3(n,q,l,m,t,C,this.w),B+=3)):G=f3(n,q,l,m,t,[I],this.w)),!G){var F=I;G=n;I=q;C=l;var M=m,U=t,fa=F.textContent?F.textContent:"",Ba=this.w[F.getAttribute("p")];F=i3(F,"t")||0;G=new D2(G+F,I-F,U,C,fa,M,Ba)}}else G=new D2(n,q,t,l,C.textContent||"",m,v);k.push(G);this.u=G}if(0<k.length)for(k[0].windowId==this.B&&(this.o=p3(this,d,e,!0),g.H(this,this.o),c.push(this.o)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,l=this.o,g.H(l,k),l.o.push(k),c.push(k)}e=c}else e=
[];return e};g.r(q3,I2);q3.prototype.gp=function(a){var b=this.A.o;I2.prototype.gp.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Ra(d,c.o);g.Ra(d,zpa);var e=c.o;var f=d}M2(this,c,d)}};
var zpa={zD:!0};g.r(r3,N2);r3.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+F2++;c=c/1E3-this.F;d=d/1E3-this.F;a=new E2(c,d-c,5,f,{textAlign:0,Yf:0,Ue:2.5*b,Kg:5.33*a});e=new D2(c,d-c,5,f,e);this.w.push(a);this.w.push(e)}};
g.r(u3,g3);u3.prototype.A=function(a){a=new r3(a,a.byteLength,this.u);if(v3(a)){for(;a.o<a.u.byteLength;)for(0==a.version?a.A=t3(a)*(1E3/45):1==a.version&&(a.A=4294967296*t3(a)+t3(a)),a.C=s3(a);0<a.C;a.C--){var b=s3(a),c=s3(a),d=s3(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.A,type:this.track,wu:c,xu:d,order:b.o.length}))}npa(this.o,a);return a.w}return[]};
u3.prototype.reset=function(){this.o.clear()};g.r(x3,I2);g.h=x3.prototype;g.h.Jz=function(){g.dn(this.ga)};
g.h.tK=function(){g.mn(this.element,"ytp-rollup-mode");this.Hh(this.Ca,!0)};
g.h.Av=function(){return this.B?this.K:this.J};
g.h.Bv=function(){return this.B?this.J:this.K};
g.h.Hh=function(a,b){this.Ca=a;if(this.A.params.Rk){for(var c=0,d=0;d<this.F.length&&c<a.length;d++)this.F[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.F.concat(a.slice(c)));this.za=this.K;this.J=this.K=0;I2.prototype.Hh.call(this,a);wpa(this,b);I2.prototype.Hh.call(this,a)}else I2.prototype.Hh.call(this,a)};g.r(z3,g3);
z3.prototype.A=function(a,b){for(var c=[],d=a.split(Apa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Bpa.test(f)){var l=S3.exec(f);if(l&&4<=l.length){var m=B3(l[1]),n=B3(l[2])-m;m+=k;var q,t=q=void 0,v=void 0,y=void 0,B=l[3];l={textAlign:2};B=g.p(B?B.split(" "):[]);for(var C=B.next();!C.done;C=B.next())if(C=C.value.split(":"),2==C.length){var G=C[1];switch(C[0]){case "line":C=G.split(",");C[0].endsWith("%")&&(y=C[0],l.Kg=Number.parseInt(y,10),2==C.length&&(v=C[1].trim()));break;case "position":C=G.split(",");
t=C[0];l.Ue=Number.parseInt(t,10);2==C.length&&(q=C[1].trim());break;case "align":switch(G){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}y||(l.Kg=100,v||(v="end"));if(!t)switch(l.textAlign){case 0:l.Ue=0;break;case 1:l.Ue=100;break;default:l.Ue=50}t=0;switch(v){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(q){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Yf=0>t||8<t?7:t;q=l;f=f.substring(S3.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=C3(m,n,5,t),n=new D2(m,n,5,k.id,q,!1,g.Zb(f)?void 0:f),c.push(k),c.push(n),g.H(k,n),k.o.push(n);else for(v=q.split(Cpa),1==v.length?(q=5,t=C3(m,n,q,t)):(y=q=6,t=Object.assign({cm:32},t),t=new E2(m,n,y,"_"+F2++,t)),c.push(t),y=m,l=0;l<v.length;l++)B=v[l],0==l%2?(C=g.LZ("<html>"+B+"</html>"),C.getElementsByTagName("parsererror").length?
(G=C.createElement("span"),G.appendChild(C.createTextNode(B))):G=C.firstChild,A3(this,y,n-(y-m),q,t,0<l,G,f,c)):y=B3(B)+k}S3.lastIndex=0}}return c};
var Bpa=/^NOTE/,Apa=/(?:\r\n|\r|\n){2,}/,S3=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Cpa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(D3,g.E);D3.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
D3.prototype.reset=function(){this.o&&this.o.reset()};
D3.prototype.Y=function(){this.clear();g.E.prototype.Y.call(this)};g.r(G3,g.oP);g.h=G3.prototype;g.h.Y=function(){if(this.B||this.H){var a=this.P.app.B;a&&a.wj()}else R3(this,!1);g.oP.prototype.Y.call(this)};
g.h.load=function(){g.oP.prototype.load.call(this);var a=!g.P(this.w.experiments,"web_player_captions_track_list_changed_killswitch");this.F=this.player.getAudioTrack();if(this.u)this.o&&(this.aa.clear(),this.B?M3(this,!0):3!=this.player.getPresentingPlayerType()&&this.u.Nq(this.o,"srv3",(0,g.x)(this.bL,this)),!a||this.B||this.H||L3(this)||this.player.la("captionschanged",p2(this.o))),a||(this.o&&!L3(this)?this.player.la("captionschanged",p2(this.o)):this.player.la("onCaptionsTrackListChanged"));
else{var b;this.ga?b=new z2(this.S.ka,this.player):this.xa?b=new u2(this.w,this.S,this.player.getAudioTrack()):b=new C2(this.S.uj,this.S.videoId,this.S.captionsLanguagePreference||this.w.captionsLanguagePreference||g.qC(this.S,"yt:cc_default_lang")||this.w.Xb,this.S.qp,this.w);this.u=b;g.H(this,this.u);b.Oq((0,g.x)(this.aL,this))}};
g.h.unload=function(){this.B&&this.o?M3(this,!1):(this.fa&&g.en(this.fa),g.uQ(this.player.app,"captions",void 0),this.J=[],this.u&&this.u.Lg(),this.aa.clear(),this.G&&g.IK(this.player,this.G),this.Rs());g.oP.prototype.unload.call(this);var a=g.S(this.player.app);a&&g.$H(a.B);this.player.la("captionschanged",{})};
g.h.create=function(){(this.ba?this.B||this.H:I3(this)||H3(this))&&this.load()};
g.h.aL=function(){var a;this.K||H3(this)?a=K3(this,this.K):I3(this)&&(a=J3(this));if(this.B||this.H){for(var b=r2(this.u.u,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Iz(e),srclang:q2(e),id:e.toString()};this.H||(f.src=this.u.Rj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Qd("TRACK",f))}a=this.P.app.B;a.oj(c);c=a.fb();this.na&&this.ea.M(c.textTracks,"change",this.cL)}else!this.o&&a&&O3(this,a),this.player.la("onCaptionsTrackListChanged"),this.player.la("onApiChange")};
g.h.cL=function(){for(var a=this.P.app.B.fb().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=r2(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.o:null)!=b&&O3(this,b,!0)};
g.h.HM=function(){!this.o&&this.B||this.unload()};
g.h.bL=function(a,b,c,d){if(a){this.u.jz()&&(this.J=[],g.uQ(this.P.app,"captions",void 0),this.Z.ii(),this.aa.reset());var e=this.aa;c=c||0;d=d||0;if("string"!==typeof a){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.rv(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!w3(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<
m&&365>m){n=a[k++];var q=a[k++],t=a[k++];m=((m&7)<<18|(n&63)<<12|(q&63)<<6|t&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],q=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|q&63)}a=f.join("")}}if(a)try{if("string"!==typeof a){var v=a,y=c,B=d;if(!w3(v))throw Error("Invalid binary caption track data");e.o||(e.o=new u3(B,b));var C=e.o.A(v,y)}else{if("WEBVTT"==a.substring(0,6)){b=a;y=c;e.o||(e.o=new z3);var G=e.o.A(b,y);.01>Math.random()&&
g.uo(Error("Deprecated subtitles format in web player: WebVTT"));v=G}else b:{G=a;y=g.LZ(G);if(!y||!y.firstChild){var I=Error("Invalid caption track data");I.params=G;throw I;}if("timedtext"==y.firstChild.tagName){if(3==parseInt(y.firstChild.getAttribute("format"),10)){if(!e.o){G={};if(B=q2(b))G.lang=B,ypa.test(B)&&(G.ze=1);e.o=new h3(G,e.u)}v=e.o.A(y,c);break b}var F=Error("Unsupported subtitles format in web player (Format2)");F.params=G;throw F;}if("transcript"==y.firstChild.tagName){var M=Error("Unsupported subtitles format in web player (Format1)");
M.params=G;throw M;}var U=Error("Invalid caption track data");U.params=G;throw U;}C=v}var fa=C}catch(Ba){g.N(Ba),e.clear(),fa=[]}else fa=[];g.IK(this.player,fa);!this.K||this.H||L3(this)||g.az(this.w)||g.bz(this.w)||(g.en(this.fa),fa=G2({Yf:0,Ue:5,Kg:5,Rk:2,textAlign:0,ze:0,lang:"vi"}),this.T=[fa],e=["Nh\u00e2\u0301p va\u0300o "," \u0111\u00ea\u0309 bi\u00ea\u0301t ca\u0300i \u0111\u0103\u0323t"],this.oa||(C=new g.Bu(g.aM()),g.H(this,C),this.oa=C.element),C=fa.end-fa.start,(b=g.Iz(this.o))&&this.T.push(new D2(fa.start,
C,0,fa.id,b)),this.T.push(new D2(fa.start,C,0,fa.id,e[0]),new D2(fa.start,C,0,fa.id,this.oa,!0),new D2(fa.start,C,0,fa.id,e[1],!0)),g.IK(this.player,this.T),g.cn(this.fa));!this.K||this.H||L3(this)||(N3(this,"module-enabled",!0),this.F&&(this.F.o=this.o),(fa=g.S(this.player.app))&&g.$H(fa.B));this.K=!1}};
g.h.HE=function(a){this.J.push(a);this.Z.ii()};
g.h.IE=function(a){g.db(this.J,a);this.u instanceof z2&&this.u.C&&g.$S(this.player.app,[a],void 0);this.Z.ii()};
g.h.OL=function(a){if(a instanceof E2){var b=this.U[a.id];b&&b.A!=a&&(b.dispose(),delete this.U[a.id],b=null);b||(b=xpa(this,a))&&(this.U[a.id]=b)}else b=a.windowId,this.V[b]||(this.V[b]=[]),this.V[b].push(a)};
g.h.UL=function(){Q3(this,this.T);this.T=null};
g.h.xA=function(){this.Z.stop();g.$b(this.V);this.J.sort(g.DD);var a=this.J;if(this.G){var b=(0,g.Zd)(a,function(c){return-1==this.G.indexOf(c)},this);
b.length&&(a=b)}(0,g.z)(a,this.OL,this);g.Lb(this.U,function(c,d){this.V[d]?(c.element.parentNode||g.MK(this.player,c.element,4),c.Hh(this.V[d])):(c.dispose(),delete this.U[d])},this)};
g.h.ZL=function(){E3(this,{},!0);g.P(this.w.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.la("captionssettingschanged")};
g.h.QC=function(){var a=P3.xb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Te?3:a.bold?1:a.Te?2:0,textOpacity:a.textOpacity,windowColor:P3.windowColor,windowOpacity:P3.windowOpacity};var b=F3(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.CA=function(a,b){var c={};g.Ra(c,F3(this,"display-settings"));g.Ra(c,a);E3(this,c,b);this.player.la("captionssettingschanged")};
g.h.Rs=function(){!this.B&&this.loaded&&(g.Lb(this.U,function(a,b){a.dispose();delete this.U[b]},this),this.xA())};
g.h.Ac=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.pd(b,-2,4);this.CA({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&O3(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.w.zb&&N3(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Na(b))break;if(g.Zb(b)){O3(this,null,!0);break}for(var d=r2(this.u.u,!0),e=0;e<d.length;e++){var f=d[e];f.u!=b.languageCode||c&&f.w!=b.languageName||(c=b.translationLanguage?hpa(f,b.translationLanguage):
f)}!c||c==this.o&&this.loaded||O3(this,c,!0)}else return this.loaded&&this.o&&!L3(this)?p2(this.o):{};return"";case "tracklist":return this.u?(0,g.ie)(r2(this.u.u,!(!b||!b.includeAsr)),function(k){return p2(k)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.B||void 0==b||R3(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.w.zb&&a.push("stickyLoading");return a};
g.h.GE=function(){var a=this.o;return a?{cc:a.C}:{}};
g.h.BM=function(){this.loaded&&this.o&&!L3(this)?(N3(this,"module-enabled",!1),this.unload(),I3(this,!0)&&O3(this,J3(this),!1)):O3(this,L3(this)||!this.o?K3(this,!0):this.o,!0)};
g.h.WH=function(){var a=L3(this);I3(this,a)?O3(this,this.player.getAudioTrack().nm,!1):this.S.captionTracks.length&&(this.loaded&&this.unload(),(this.ba?this.B||this.H:I3(this)||H3(this))&&(a?O3(this,K3(this),!1):this.load()))};g.DP.captions=G3;})(_yt_player);
